name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/security-cicd:latest

	- name: List workspace content
	  run: ls -al $GITHUB_WORKSPACE
	  
    - name: Deploy to Localhost
      run: |
        sudo cp -r $GITHUB_WORKSPACE/* /var/www/html/
        sudo chown -R www-data:www-data /var/www/html/
        sudo systemctl restart apache2
        
    - name: Verify Deployment
      run: |
        echo "Ready For Deployment"
        
