name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: WHOAMI
      run: whoami

    - name: Deploy to Localhost
      run: |
        sudo cp -r $GITHUB_WORKSPACE/* /var/www/html/
        sudo chown -R www-data:www-data /var/www/html/
        sudo systemctl restart apache2
        ls -al /var/www/html/
        
    - name: Verify Deployment
      run: |
        curl http://localhost
        
